# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('wallet', models.IntegerField()),
                ('amount_bet', models.IntegerField()),
                ('team_bet', models.CharField(max_length=3)),
                ('player_name', models.CharField(max_length=32)),
            ],
        ),
    ]
