# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='amount_bet',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='pid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='player',
            name='team_bet',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='player',
            name='wallet',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
