# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting_app', '0002_auto_20171118_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(default='', max_length=30)),
                ('team_id', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
            ],
            options={
                'ordering': ('rank',),
            },
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ('wallet',)},
        ),
    ]
